name: Deploy Cloud Function

on:
  push:
    branches: 
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 12

      - name: Install packages
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Copy node_modules to build folder
        run: cp -r node_modules/ build/

      - name: Deploy to GCP
        uses: google-github-actions/deploy-cloud-functions@main
        id: deploy
        with:
          project_id: bnguyensn-2468
          name: get-github-access-token
          description: A GCP HTTP cloud function that act as a middleware server to get GitHub access tokens
          runtime: nodejs12
          region: europe-west2
          credentials: ${{ secrets.GCP_CREDENTIALS }}
          source_dir: build
          entry_point: getAccessToken
          env_vars: CLIENT_ID=${{ secrets.CLIENT_ID }},CLIENT_SECRET=${{ secrets.CLIENT_SECRET }},CORS_ORIGIN=${{ secrests.ALLOWED_ORIGINS }}
